# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: Eleftherios Mylonas
email: lefterismyl@gmail.com
description: Personal website of Eleftherios Mylonas.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
# last_updated: true

icon: 💻 # the emoji used as the favicon
url: 
blog_name: blog
blog_description: Personal blog of Eleftherios Mylonas

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
orcid_id: 0000-0002-7676-685X # your ORCID ID
scholar_userid: # your Google Scholar ID
github_username: lefmylonas
linkedin_username: eleftherios-mylonas
research_gate_profile: Eleftherios-Mylonas # your profile on ResearchGate
facebook_username: # your Facebook handle
twitter_username: # your Twitter handle
contact_note: Feel free to drop me a line via email.

google_analytics: UA-XXXXXXXXX

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge
highlight_theme: monokai
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Include/Exclude
include: ['_pages']
exclude: [node_modules]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Mylonas
  first_name: [Eleftherios, E.]
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
